In [1]:
import pandas as pd

df = pd.read_csv("Data/Challenge/Mixure_Definitions_Training_set.csv")
df

,Dataset,Mixture Label,CID,CID.1,CID.2,CID.3,CID.4,CID.5,CID.6,CID.7,...,CID.48,CID.49,CID.50,CID.51,CID.52,CID.53,CID.54,CID.55,CID.56,CID.57
0,Snitz 1,1,6501,264,2879,7685,7731,326,7888,61138,...,0,0,0,0,0,0,0,0,0,0
1,Snitz 1,2,240,93009,323,8148,7762,3314,460,6184,...,0,0,0,0,0,0,0,0,0,0
2,Snitz 1,3,7710,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Snitz 1,4,31276,93009,11002,323,7966,8148,7632,22201,...,0,0,0,0,0,0,0,0,0,0
4,Snitz 1,5,10890,93009,11002,6982,323,8797,7966,8148,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698,Bushdid,516,16666,19310,62465,22201,12473,22386,7583,7762,...,0,0,0,0,0,0,0,0,0,0
699,Bushdid,517,0,10821,0,8148,3776,8048,7731,31249,...,0,0,0,0,0,0,0,0,0,0
700,Bushdid,518,6561,12473,7590,24915,261,14100,997,8030,...,0,0,0,0,0,0,0,0,0,0
701,Bushdid,519,2969,264,8048,6054,4133,8635,10560,12348,...,0,0,0,0,0,0,0,0,0,0
702,Bushdid,520,2969,264,8048,6054,4133,8635,10560,12348,...,0,0,0,0,0,0,0,0,0,0

In [2]:
# Function to extract Mixture Label and all non-zero CIDs as a list
def extract_mixture_labels_and_cids(df):
    result = []
    cid_columns = [col for col in df.columns if col.startswith('CID')]

    for index, row in df.iterrows():
        mixture_label = row['Mixture Label']
        cids = [cid for cid in row[cid_columns].tolist() if cid != 0]
        if 11002307 in cids:
            cids.remove(11002307)
            cids.append(11002)
            cids.append(307)
        result.append({"label":mixture_label, "cids":cids})

    return result

# Get the result
results = extract_mixture_labels_and_cids(df)

# Display the result
len(results), results[0]

(703,
 {'label': 1,
  'cids': [6501, 264, 2879, 7685, 7731, 326, 7888, 61138, 8030, 1183]})

In [3]:
smiles_df = pd.read_csv("Data/molecules.csv")
smiles_df = smiles_df.set_index("CID")
cid_to_smiles = smiles_df.to_dict(orient="index")
len(cid_to_smiles), next(iter(cid_to_smiles.items()))

(174, (176, {'SMILES': 'CC(=O)O'}))

In [5]:
missing = set()
for mixture in results:
    for cid in mixture["cids"]:
        assert cid in cid_to_smiles
missing

set()